/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/**/*.html", "./static/**/*.js", "./static/**/*.css", "node_modules/preline/dist/*.js", "./node_modules/flowbite/**/*.js"],
  theme: {
    extend: {
      keyframes: {
        slideIn: {
          "0%": { transform: "translateX(-100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
      },
      animation: {
        slideIn: "slideIn 0.5s ease-out forwards",
      },
      colors: {
        blueshade: "#3498db",
        greenshade: "#2ecc71",
        backgroundshade: "#ecf0f1",
        accentshade: "##e74c3c",
        yellowshade: "##f1c40f",
        warmBeige: "#F4F0E6",
        mutedCocoa: "#A67B5B",
        ivory: "#FFFFF0",
        softGold: "#D1B794",
        softGoldHover: "#C1A682",
        pastelOrange: "#E8B97E",
        subduedGreen: "#A4B89F",
        darkTaupe: "#4B4843",
        deepGreen: "#8E9E8D",
        offWhite: "#F9F6EF",
        lightGray: "#E2E0DD",
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
      },
    },
    fontFamily: {
      body: [
        "Roboto",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Roboto",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  plugins: [
    require("preline/plugin"),
    require("flowbite/plugin")({
      datatables: true,
    }),
  ],
};
